replicaCount: 1

image:
  repository: link-shortener-user-service
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  name: link-shortener-user-service

spring:
  profiles:
    active: "default"

resources:
  requests:
    cpu: "50m"
    memory: "384Mi"
  limits:
    cpu: "1"
    memory: "768Mi"

env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=65.0 -XX:+UseSerialGC"

vault:
  role: ""
  secretPath: ""
  secretTemplate: ""
  agent:
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"